apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-custom-role
  namespace: argocd
rules:
  - apiGroups: ['argoproj.io']
    resources: ['workflowtaskresults']
    verbs: ['create', 'update', 'patch']
