apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-custom-role-binding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: default
    namespace: argocd
roleRef:
  kind: Role
  name: argo-workflows-custom-role
  apiGroup: rbac.authorization.k8s.io
