apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    g, jane, proj:team-a:read-write
    g, jane, proj:team-b:read-only
    g, david, proj:team-b:read-write
    p, infra, applications, *, */*, allow
    p, infra, projects, get, *, allow       


