apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ['missingkey=error']
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/visheshofficial/argo-cd.git
              revision: HEAD
              files:
                - path: 'applicationset/examples/git-generator-files-discovery/cluster-config/**/config.yaml'
                - path: 'applicationset/examples/git-generator-files-discovery/cluster-config/**/config.json'
          - clusters:
              selector:
                matchLabels:
                  environment: dev
  template:
    metadata:
      name: '{{.cluster.name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/visheshofficial/argo-cd.git
        targetRevision: HEAD
        path: 'applicationset/examples/git-generator-files-discovery/apps/guestbook'
      destination:
        server: '{{.server}}'
        #server: '{{.cluster.address}}'
        namespace: dev2
