apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-example
  namespace: argocd
spec:
  project: default
  sources:
    - path: argocd/40-argo-syncwaves-and-hooks/10-syncwaves/30-hook-example/10-manifests
      repoURL: https://github.com/visheshofficial/gitops
      targetRevision: master
    - path: argocd/40-argo-syncwaves-and-hooks/10-syncwaves/30-hook-example/20-hooks
      repoURL: https://github.com/visheshofficial/gitops
      targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-syncwaves-and-hooks
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
