apiVersion: batch/v1
kind: Job
metadata:
  generateName: postsync-job
  namespace: argo-syncwaves-and-hooks
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
        - name: postsync-job-success
          image: ubuntu
          command:
            - /bin/bash
            - -c
            - |
              echo "This is Post-Sync"
      restartPolicy: Never
