kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argo-quickstart
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080 # Argo CD dashboard
        hostPort: 30080
      # - containerPort: 30443
      # hostPort: 30443
      - containerPort: 32746 # Argo Workflows UI
        hostPort: 32746
      - containerPort: 9001 # Minio UI
        hostPort: 9001
      - containerPort: 9000 # Minio
        hostPort: 9000
# - role: worker
# - role: worker
