# apiVersion: v1
# kind: Namespace
# metadata:
#   name: my-app
# ---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  # namespace: my-app
spec:
  containers:
    - name: demo-container
      image: busybox
      command:
        [
          'sh',
          '-c',
          'echo Database user: $DB_USER && echo Database password: $DB_PASS && sleep 3600',
        ]
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-database-secret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: my-database-secret
              key: password
