apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-database-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: my-database-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: my-database-secret # Must match the secret name in AWS Secrets Manager.
        property: username # The JSON property to extract.
    - secretKey: password
      remoteRef:
        key: my-database-secret
        property: password
