apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: argo-syncwaves-and-hooks
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  selector:
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
