apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  namespace: argo-syncwaves-and-hooks
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: main
          image: nginx:latest
